apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: daniel.chuchulev96@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-private-key
    solvers:
    - dns01:
        route53:
          region: eu-central-1
          hostedZoneID: Z04677662LQDVENYJPMKD # Must match the ID in your Policy